version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "test.harryseong.com"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --configuration=test
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/harryseong'